### ISSUE TITLE
7f67588e6 explodes with invalid UTF-8 in fish_history

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#10102]
I've no idea how, but apparently I've got some invalid UTF-8 in my `fish_history`, which makes the current build unhappy.

Debian 11, rustc 1.76.0-nightly (dd430bc8c 2023-11-14) and 1.73.0.

```
thread '<unnamed>' panicked at fish-rust/src/history/file.rs:308:5:
assertion failed: std::str::from_utf8(s).is_ok()
stack backtrace:
   0:     0x56009acff16c - std::backtrace_rs::backtrace::libunwind::trace::hd064118b065dd415
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56009acff16c - std::backtrace_rs::backtrace::trace_unsynchronized::hbb93ce2a1e047222
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56009acff16c - std::sys_common::backtrace::_print_fmt::h8fe0686eaa20a73c
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56009acff16c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd0db499a690ef92f
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56009ad6281c - core::fmt::rt::Argument::fmt::h563374216252b56c
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/fmt/rt.rs:138:9
   5:     0x56009ad6281c - core::fmt::write::hbff0e0b8a6a5ff52
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/fmt/mod.rs:1114:21
   6:     0x56009acf353e - std::io::Write::write_fmt::h53a1b8b6d8649f4a
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/io/mod.rs:1763:15
   7:     0x56009acfef54 - std::sys_common::backtrace::_print::h7e9afd72f60b90ce
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x56009acfef54 - std::sys_common::backtrace::print::h423bc9d72f47ea21
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x56009ad01e33 - std::panicking::default_hook::{{closure}}::h59fa9e892cc0fcf3
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:272:22
  10:     0x56009ad01b54 - std::panicking::default_hook::ha0b647f23d45a599
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:292:9
  11:     0x56009ad02475 - std::panicking::rust_panic_with_hook::hc05e318e4106412d
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:731:13
  12:     0x56009ad02326 - std::panicking::begin_panic_handler::{{closure}}::h69236f0387b62eeb
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:601:13
  13:     0x56009acff696 - std::sys_common::backtrace::__rust_end_short_backtrace::h41200384bcce0ad0
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x56009ad020c2 - rust_begin_unwind
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:597:5
  15:     0x56009a7ae7a5 - core::panicking::panic_fmt::h5969185a75f0fa67
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/panicking.rs:72:14
  16:     0x56009a7ae843 - core::panicking::panic::hf6b928d7ac102597
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/panicking.rs:127:5
  17:     0x56009af0f0ac - fish_rust::history::file::unescape_yaml_fish_2_0::h29fc63b171fae3c5
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/history/file.rs:308:5
  18:     0x56009af0fdd6 - fish_rust::history::file::decode_item_fish_2_0::h7b188b88b3e29227
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/history/file.rs:410:17
  19:     0x56009af0e016 - fish_rust::history::file::HistoryFileContents::decode_item::h280045b7735b989e
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/history/file.rs:152:9
  20:     0x56009a952e23 - fish_rust::history::HistoryImpl::item_at_index::h2bb51283649c2052
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/history.rs:1433:24
  21:     0x56009a956409 - fish_rust::history::History::item_at_index::hce521bb38c28f725
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/history.rs:1919:9
  22:     0x56009a956c2d - fish_rust::history::HistorySearch::go_to_next_match::hac0ecbd560b01958
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/history.rs:2031:30
  23:     0x56009a92b4c8 - fish_rust::history::history_ffi::_::__HistorySearch__go_to_next_match::__HistorySearch__go_to_next_match::h1bf8afa2c38ddfe7
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/history.rs:218:14
  24:     0x56009ae0e70f - fish_rust::history::history_ffi::_::__HistorySearch__go_to_next_match::{{closure}}::h08bdb6cbcc76cb8c
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/history.rs:80:1
  25:     0x56009a87eed2 - cxx::unwind::prevent_unwind::h9a69ef6d9985c249
                               at /home/wheel/zanchey/.cargo/git/checkouts/cxx-1b6cf865eed67274/3064cb4/src/unwind.rs:23:15
  26:     0x56009a92b499 - cxxbridge1$HistorySearch$go_to_next_match
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/history.rs:228:75
  27:     0x56009abaa11b - _ZN13HistorySearch16go_to_next_matchE15SearchDirection
                               at /home/wheel/zanchey/src/fish-shell/build/./cargo/build/x86_64-unknown-linux-gnu/debug/build/fish-rust-55873d63f4952620/out/cxxbridge/sources/fish-rust/fish-rust/src/history.rs.cc:992:51
  28:     0x56009a7eff92 - operator()
                               at /home/wheel/zanchey/src/fish-shell/src/reader.cpp:2040:42
  29:     0x56009a8029f2 - __invoke_impl<(anonymous namespace)::autosuggestion_t, get_autosuggestion_performer(const parser_t&, const wcstring&, size_t, const HistorySharedPtr&)::<lambda()>&>
                               at /usr/include/c++/10/bits/invoke.h:60:67
  30:     0x56009a80103f - __invoke_r<(anonymous namespace)::autosuggestion_t, get_autosuggestion_performer(const parser_t&, const wcstring&, size_t, const HistorySharedPtr&)::<lambda()>&>
                               at /usr/include/c++/10/bits/invoke.h:142:36
  31:     0x56009a7fee0c - _M_invoke
                               at /usr/include/c++/10/bits/std_function.h:292:44
  32:     0x56009a7ff1a1 - operator()
                               at /usr/include/c++/10/bits/std_function.h:622:71
  33:     0x56009a7fd58b - operator()
                               at /home/wheel/zanchey/src/fish-shell/src/iothread.h:50:18
  34:     0x56009a806556 - __invoke_impl<void*, debounce_perform_with_completion<(anonymous namespace)::autosuggestion_t>::<lambda(void const*)>&, void const*>
                               at /usr/include/c++/10/bits/invoke.h:60:36
  35:     0x56009a805e54 - __invoke_r<void*, debounce_perform_with_completion<(anonymous namespace)::autosuggestion_t>::<lambda(void const*)>&, void const*>
                               at /usr/include/c++/10/bits/invoke.h:141:40
  36:     0x56009a805652 - _M_invoke
                               at /usr/include/c++/10/bits/std_function.h:291:30
  37:     0x56009abadcf1 - _ZNKSt8functionIFPvPKvEEclES2_
                               at /usr/include/c++/10/bits/std_function.h:622:14
  38:     0x56009abad92b - _ZNK10callback_t6invokeEv
                               at /home/wheel/zanchey/src/fish-shell/src/callback.h:30:38
  39:     0x56009abad9c6 - cxxbridge1$callback_t$invoke
                               at /home/wheel/zanchey/src/fish-shell/build/./cargo/build/x86_64-unknown-linux-gnu/debug/build/fish-rust-55873d63f4952620/out/cxxbridge/sources/fish-rust/fish-rust/src/threads.rs.cc:271:25
  40:     0x56009a9412db - fish_rust::threads::ffi::CppCallback::invoke::h9ed0386067d42dba
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:59:12
  41:     0x56009a8b12db - fish_rust::threads::Debounce::perform_with_completion_ffi::{{closure}}::hd1b0b92b2199f6d2
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:698:47
  42:     0x56009a8b1488 - fish_rust::threads::Debounce::perform_with_completion::{{closure}}::h10c07285f4625255
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:721:26
  43:     0x56009aabc56e - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4b5a5af539c3e94c
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/ops/function.rs:250:5
  44:     0x56009a94a398 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h750cc19b87cc40d6
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/alloc/src/boxed.rs:2007:9
  45:     0x56009ab870f2 - fish_rust::threads::Debounce::run_next::hd47d41cf94d4e340
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:667:9
  46:     0x56009a8b15fd - fish_rust::threads::Debounce::perform_inner::{{closure}}::h55ad7ebfeeadbf31
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:759:23
  47:     0x56009aabd0be - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc3cad64e3447c1ff
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/ops/function.rs:250:5
  48:     0x56009a94a398 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h750cc19b87cc40d6
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/alloc/src/boxed.rs:2007:9
  49:     0x56009ab85b75 - fish_rust::threads::WorkerThread::run::h23fb78ec1bd9985f
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:488:13
  50:     0x56009a8b0b67 - fish_rust::threads::ThreadPool::spawn_thread::{{closure}}::h8bf149823c479f47
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:464:13
  51:     0x56009a8b05f3 - fish_rust::threads::spawn::{{closure}}::h11c2947c957ce3a7
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:271:9
  52:     0x56009a97a563 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9976e58ad5a09a4f
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys_common/backtrace.rs:154:18
  53:     0x56009aeb1b23 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hb6ae4cb3d2d4e043
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/thread/mod.rs:529:17
  54:     0x56009aa7d873 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h982a4204f15d99c1
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/panic/unwind_safe.rs:271:9
  55:     0x56009aa5ea16 - std::panicking::try::do_call::h36d5edbfc1973bce
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:504:40
  56:     0x56009aa5f5fb - __rust_try
  57:     0x56009aa5e97e - std::panicking::try::he5a0cc5907bd8249
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:468:19
  58:     0x56009aeb0dee - std::panic::catch_unwind::h84ba02808ae5aa00
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panic.rs:142:14
  59:     0x56009aeb0dee - std::thread::Builder::spawn_unchecked_::{{closure}}::h2eccf39827485060
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/thread/mod.rs:528:30
  60:     0x56009aabcafe - core::ops::function::FnOnce::call_once{{vtable.shim}}::h7d19fb40ed2c2d2c
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/ops/function.rs:250:5
  61:     0x56009ad0d105 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7aef1453107c3c80
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/alloc/src/boxed.rs:2007:9
  62:     0x56009ad0d105 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8d5d8dcd4ee7aacb
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/alloc/src/boxed.rs:2007:9
  63:     0x56009ad0d105 - std::sys::unix::thread::Thread::new::thread_start::had02eac1ec4f7b1b
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys/unix/thread.rs:108:17
  64:     0x7fce15087ea7 - start_thread
                               at ./nptl/pthread_create.c:477:8
  65:     0x7fce14bc1a2f - clone
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  66:                0x0 - <unknown>
thread '<unnamed>' panicked at /home/wheel/zanchey/.cargo/git/checkouts/cxx-1b6cf865eed67274/3064cb4/src/unwind.rs:37:9:
panic in ffi function fish_rust::history::history_ffi::HistorySearch::go_to_next_match, aborting.
stack backtrace:
thread '<unnamed>' panicked at  fish-rust/src/history.rs : 16430:: 23 :
 called `Result::unwrap()` on an `Err` value: PoisonError { .. }
 0x56009acff16c - std::backtrace_rs::backtrace::libunwind::trace::hd064118b065dd415
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56009acff16c - std::backtrace_rs::backtrace::trace_unsynchronized::hbb93ce2a1e047222
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56009acff16c - std::sys_common::backtrace::_print_fmt::h8fe0686eaa20a73c
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56009acff16c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd0db499a690ef92f
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56009ad6281c - core::fmt::rt::Argument::fmt::h563374216252b56c
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/fmt/rt.rs:138:9
   5:     0x56009ad6281c - core::fmt::write::hbff0e0b8a6a5ff52
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/fmt/mod.rs:1114:21
   6:     0x56009acf353e - std::io::Write::write_fmt::h53a1b8b6d8649f4a
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/io/mod.rs:1763:15
   7:     0x56009acfef54 - std::sys_common::backtrace::_print::h7e9afd72f60b90ce
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x56009acfef54 - std::sys_common::backtrace::print::h423bc9d72f47ea21
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x56009ad01e33 - std::panicking::default_hook::{{closure}}::h59fa9e892cc0fcf3
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:272:22
  10:     0x56009ad01b54 - std::panicking::default_hook::ha0b647f23d45a599
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:292:9
  11:     0x56009ad02475 - std::panicking::rust_panic_with_hook::hc05e318e4106412d
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:731:13
  12:     0x56009ad02371 - std::panicking::begin_panic_handler::{{closure}}::h69236f0387b62eeb
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:609:13
  13:     0x56009acff696 - std::sys_common::backtrace::__rust_end_short_backtrace::h41200384bcce0ad0
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x56009ad020c2 - rust_begin_unwind
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:597:5
  15:     0x56009a7ae7a5 - core::panicking::panic_fmt::h5969185a75f0fa67
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/panicking.rs:72:14
  16:     0x56009ac828f3 - <cxx::unwind::Guard as core::ops::drop::Drop>::drop::h6c320d84126d5230
                               at /home/wheel/zanchey/.cargo/git/checkouts/cxx-1b6cf865eed67274/3064cb4/src/unwind.rs:37:9
  17:     0x56009aac8a0b - core::ptr::drop_in_place<cxx::unwind::Guard>::ha22b9dc1994a0d76
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/ptr/mod.rs:497:1
  18:     0x56009a87ef4c - cxx::unwind::prevent_unwind::h9a69ef6d9985c249
                               at /home/wheel/zanchey/.cargo/git/checkouts/cxx-1b6cf865eed67274/3064cb4/src/unwind.rs:28:1
  19:     0x56009a92b499 - cxxbridge1$HistorySearch$go_to_next_match
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/history.rs:228:75
  20:     0x56009abaa11b - _ZN13HistorySearch16go_to_next_matchE15SearchDirection
                               at /home/wheel/zanchey/src/fish-shell/build/./cargo/build/x86_64-unknown-linux-gnu/debug/build/fish-rust-55873d63f4952620/out/cxxbridge/sources/fish-rust/fish-rust/src/history.rs.cc:992:51
  21:     0x56009a7eff92 - operator()
                               at /home/wheel/zanchey/src/fish-shell/src/reader.cpp:2040:42
  22:     0x56009a8029f2 - __invoke_impl<(anonymous namespace)::autosuggestion_t, get_autosuggestion_performer(const parser_t&, const wcstring&, size_t, const HistorySharedPtr&)::<lambda()>&>
                               at /usr/include/c++/10/bits/invoke.h:60:67
  23:     0x56009a80103f - __invoke_r<(anonymous namespace)::autosuggestion_t, get_autosuggestion_performer(const parser_t&, const wcstring&, size_t, const HistorySharedPtr&)::<lambda()>&>
                               at /usr/include/c++/10/bits/invoke.h:142:36
  24:     0x56009a7fee0c - _M_invoke
                               at /usr/include/c++/10/bits/std_function.h:292:44
  25:     0x56009a7ff1a1 - operator()
                               at /usr/include/c++/10/bits/std_function.h:622:71
  26:     0x56009a7fd58b - operator()
                               at /home/wheel/zanchey/src/fish-shell/src/iothread.h:50:18
  27:     0x56009a806556 - __invoke_impl<void*, debounce_perform_with_completion<(anonymous namespace)::autosuggestion_t>::<lambda(void const*)>&, void const*>
                               at /usr/include/c++/10/bits/invoke.h:60:36
  28:     0x56009a805e54 - __invoke_r<void*, debounce_perform_with_completion<(anonymous namespace)::autosuggestion_t>::<lambda(void const*)>&, void const*>
                               at /usr/include/c++/10/bits/invoke.h:141:40
  29:     0x56009a805652 - _M_invoke
                               at /usr/include/c++/10/bits/std_function.h:291:30
  30:     0x56009abadcf1 - _ZNKSt8functionIFPvPKvEEclES2_
                               at /usr/include/c++/10/bits/std_function.h:622:14
  31:     0x56009abad92b - _ZNK10callback_t6invokeEv
                               at /home/wheel/zanchey/src/fish-shell/src/callback.h:30:38
  32:     0x56009abad9c6 - cxxbridge1$callback_t$invoke
                               at /home/wheel/zanchey/src/fish-shell/build/./cargo/build/x86_64-unknown-linux-gnu/debug/build/fish-rust-55873d63f4952620/out/cxxbridge/sources/fish-rust/fish-rust/src/threads.rs.cc:271:25
  33:     0x56009a9412db - fish_rust::threads::ffi::CppCallback::invoke::h9ed0386067d42dba
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:59:12
  34:     0x56009a8b12db - fish_rust::threads::Debounce::perform_with_completion_ffi::{{closure}}::hd1b0b92b2199f6d2
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:698:47
  35:     0x56009a8b1488 - fish_rust::threads::Debounce::perform_with_completion::{{closure}}::h10c07285f4625255
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:721:26
  36:     0x56009aabc56e - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4b5a5af539c3e94c
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/ops/function.rs:250:5
  37:     0x56009a94a398 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h750cc19b87cc40d6
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/alloc/src/boxed.rs:2007:9
  38:     0x56009ab870f2 - fish_rust::threads::Debounce::run_next::hd47d41cf94d4e340
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:667:9
  39:     0x56009a8b15fd - fish_rust::threads::Debounce::perform_inner::{{closure}}::h55ad7ebfeeadbf31
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:759:23
  40:     0x56009aabd0be - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc3cad64e3447c1ff
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/ops/function.rs:250:5
  41:     0x56009a94a398 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h750cc19b87cc40d6
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/alloc/src/boxed.rs:2007:9
  42:     0x56009ab85b75 - fish_rust::threads::WorkerThread::run::h23fb78ec1bd9985f
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:488:13
  43:     0x56009a8b0b67 - fish_rust::threads::ThreadPool::spawn_thread::{{closure}}::h8bf149823c479f47
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:464:13
  44:     0x56009a8b05f3 - fish_rust::threads::spawn::{{closure}}::h11c2947c957ce3a7
                               at /home/wheel/zanchey/src/fish-shell/fish-rust/src/threads.rs:271:9
  45:     0x56009a97a563 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9976e58ad5a09a4f
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys_common/backtrace.rs:154:18
  46:     0x56009aeb1b23 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hb6ae4cb3d2d4e043
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/thread/mod.rs:529:17
  47:                     0x56009aa7d873 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h982a4204f15d99c1
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/panic/unwind_safe.rs:271:9
  48:     0x56009aa5ea16 - std::panicking::try::do_call::h36d5edbfc1973bce
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:504:40
  49:     0x56009aa5f5fb - __rust_try
  50:     0x56009aa5e97e - std::panicking::try::he5a0cc5907bd8249
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:468:19
  51:     0x56009aeb0dee - std::panic::catch_unwind::h84ba02808ae5aa00
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panic.rs:142:14
  52:     0x56009aeb0dee - std::thread::Builder::spawn_unchecked_::{{closure}}::h2eccf39827485060
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/thread/mod.rs:528:30
  53:     0x56009aabcafe - core::ops::function::FnOnce::call_once{{vtable.shim}}::h7d19fb40ed2c2d2c
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/ops/function.rs:250:5
  54:     0x56009ad0d105 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7aef1453107c3c80
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/alloc/src/boxed.rs:2007:9
  55:     0x56009ad0d105 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8d5d8dcd4ee7aacb
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/alloc/src/boxed.rs:2007:9
  56:     0x56009ad0d105 - std::sys::unix::thread::Thread::new::thread_start::had02eac1ec4f7b1b
                               at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/sys/unix/thread.rs:108:17
  57:     0x7fce15087ea7 - start_thread
                               at ./nptl/pthread_create.c:477:8
  58:     0x7fce14bc1a2f - clone
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  59:                0x0 - <unknown>
stack backtrace:
thread '<unnamed>' panicked at library/core/src/panicking.rs : 144: 50:
: panic in a destructor during cleanup
 thread caused non-unwinding panic. aborting.
  0x56009acff16c - std
```

**Comment by zanchey** [comment]
The `fish_history` entry looks like this in vim, so I guess I had a weird path at some stage that I was mucking around with.

```
- cmd: rm \\X90\\X9e\\>\\ca
  when: 1383009865
  paths:
    - <90><9e>>^A
 ```

**Comment by faho** [comment]
You apparently had a path that wasn't valid UTF-8 - which *is allowed* in POSIX.

https://github.com/fish-shell/fish-shell/blob/7f67588e63a485b32ae00f56836d646152cd992b/fish-rust/src/history/file.rs#L410

which calls "unescape_yaml_fish_2_0", which debug_asserts:

https://github.com/fish-shell/fish-shell/blob/7f67588e63a485b32ae00f56836d646152cd992b/fish-rust/src/history/file.rs#L308

The issue here is that paths actually do not have to be valid utf-8.

**Comment by faho** [comment]
Or quite possibly the assert is just bogus - I'm not sure if this wouldn't just work without (we call str2wcstring, which should be able to deal with it).

**Comment by krobelus** [comment]
yeah we didn't have this assert in C++ either.
I had removed some code that incorrectly assumed UTF-8 but I missed this one. We can't use `String`/`str` for user input.

**Comment by krobelus** [comment]
`unescape_yaml_fish_2_0` used to take a `&mut str`
