### ISSUE TITLE
Running `commandline --help` causes a panic

### ISSUE THREAD

**Issue by Humandoodlebug** [fish-shell/fish-shell#10342]
fish, version 3.7.0-1484-ga1e46a94f
OS: Arch Linux, kernel: 6.6.18-1-lts
Terminal: Konsole 23.08.5-1
Rust Toolchain: 1.76.0
Same behaviour with/without third-party customisations.

I experienced this on a properly installed version of fish, but ran through cargo in debug mode to get a (hopefully) useful stack trace:

```
$ sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= RUST_BACKTRACE=1 target/debug/fish'                                                                                                         5.5m  Mon 04 Mar 2024 15:41:07 GMT
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
[REDACTED]> commandline --help
thread 'main' panicked at src/parser.rs:786:27:
already borrowed: BorrowMutError
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::cell::panic_already_borrowed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/cell.rs:761:5
   3: core::cell::RefCell<T>::borrow_mut
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/cell.rs:1051:25
   4: fish::parser::Parser::libdata_mut
             at ./src/parser.rs:786:9
   5: fish::proc::process_clean_after_marking::{{closure}}
             at ./src/proc.rs:1692:44
   6: fish::common::scoped_push_replacer
             at ./src/common.rs:1881:17
   7: fish::proc::process_clean_after_marking
             at ./src/proc.rs:1691:21
   8: fish::proc::job_reap
             at ./src/proc.rs:1169:5
   9: fish::parser::Parser::eval_node
             at ./src/parser.rs:556:9
  10: fish::parser::Parser::eval_parsed_source
             at ./src/parser.rs:495:13
  11: fish::parser::Parser::eval_with
             at ./src/parser.rs:463:20
  12: fish::parser::Parser::eval
             at ./src/parser.rs:438:9
  13: fish::builtins::shared::builtin_print_help_error
             at ./src/builtins/shared.rs:560:15
  14: fish::builtins::shared::builtin_print_help
             at ./src/builtins/shared.rs:539:5
  15: fish::builtins::commandline::commandline
             at ./src/builtins/commandline.rs:278:17
  16: fish::builtins::shared::builtin_run
             at ./src/builtins/shared.rs:411:23
  17: fish::exec::get_performer_for_builtin::{{closure}}
             at ./src/exec.rs:1157:13
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  20: fish::exec::exec_builtin_process
             at ./src/exec.rs:1177:18
  21: fish::exec::exec_process_in_job
             at ./src/exec.rs:1315:33
  22: fish::exec::exec_job
             at ./src/exec.rs:159:12
  23: fish::parse_execution::ParseExecutionContext::run_1_job
             at ./src/parse_execution.rs:1691:21
  24: fish::parse_execution::ParseExecutionContext::run_job_conjunction
             at ./src/parse_execution.rs:1771:26
  25: fish::parse_execution::ParseExecutionContext::test_and_run_1_job_conjunction
             at ./src/parse_execution.rs:1758:13
  26: fish::parse_execution::ParseExecutionContext::run_job_list
             at ./src/parse_execution.rs:1807:22
  27: fish::parse_execution::ParseExecutionContext::eval_job_list
             at ./src/parse_execution.rs:257:9
  28: fish::parse_execution::ParseExecutionContext::eval_node
             at ./src/parse_execution.rs:186:17
  29: fish::parser::Parser::eval_node
             at ./src/parser.rs:590:13
  30: fish::parser::Parser::eval_parsed_source
             at ./src/parser.rs:495:13
  31: fish::parser::Parser::eval_with
             at ./src/parser.rs:463:20
  32: fish::parser::Parser::eval
             at ./src/parser.rs:438:9
  33: fish::reader::reader_run_command
             at ./src/reader.rs:4596:20
  34: fish::reader::read_i
             at ./src/reader.rs:616:24
  35: fish::reader::reader_read
             at ./src/reader.rs:567:9
  36: fish::main
             at ./src/bin/fish.rs:676:15
  37: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Humandoodlebug** [comment]
Damn, that was fast! :100:
