### ISSUE TITLE
`TryFromIntError` when typing the letter `h`

### ISSUE THREAD

**Issue by lgarron** [fish-shell/fish-shell#10836]
fish version: `fish, version 3.7.1-2473-g373c5b1e1` (from `brew install --HEAD fish` using [this commit](https://github.com/fish-shell/fish-shell/commit/373c5b1e148ae34a8fe38dba8c8506f998e0c549))
macOS 15.1

1. Launch `fish`
2. Type `h`

Result:

```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
lgarron@Germain /Users/lgarron > hthread 'main' panicked at src/screen.rs:1956:42:
called `Result::unwrap()` on an `Err` value: TryFromIntError(())
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish crashed, please report a bug. Debug PID 76657 or press Enter to exit
```

Repro details:

- This happens even if I comment out all the contents of my `config.fish` file.
- This does not happen if I use `fish` to launch another shell using `fish --no-config` and type `h` inside that shell.
- This *does* happen if I use `fish` to launch another shell using `fish` and type `h` inside that shell.
- This does not happen if I move `/Users/lgarron/.config/fish/`.
- This doesn't seem to happen for any other letter.
- The full backtrace is:

```
thread 'main' panicked at src/screen.rs:1956:42:
called `Result::unwrap()` on an `Err` value: TryFromIntError(())
stack backtrace:
   0:        0x1043823ec - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h192489893ab3de20
   1:        0x10418ac60 - core::fmt::write::h2573968dce8b4c8e
   2:        0x1043820f4 - std::io::Write::write_fmt::hd688b4e0e14280fb
   3:        0x104378290 - std::panicking::default_hook::{{closure}}::h132ab4fd80cbd688
   4:        0x104377e90 - std::panicking::default_hook::h25db1205ededf4a8
   5:        0x10435908c - fish::panic::panic_handler::{{closure}}::he5d07eba9ddcfd95
   6:        0x1043797b8 - std::panicking::rust_panic_with_hook::h1a5e700ba9552453
   7:        0x104384ee4 - std::panicking::begin_panic_handler::{{closure}}::h4b087c40eb4a42d9
   8:        0x104384e58 - std::sys::backtrace::__rust_end_short_backtrace::heff777664c13f8e2
   9:        0x1043786b4 - _rust_begin_unwind
  10:        0x104396180 - core::panicking::panic_fmt::h681f622c7f427738
  11:        0x104396454 - core::result::unwrap_failed::h1f19f54c79dd8694
  12:        0x104349a68 - fish::screen::Screen::write::h64eba150c1548389
  13:        0x104323314 - fish::reader::Reader::paint_layout::hb7a7da5de25b8bc7
  14:        0x1041db5a4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4a5b90dd3ecf5c2c
  15:        0x1041d82bc - fish::threads::iothread_service_main::h04dbc998be0897b4
  16:        0x10431543c - fish::input_common::InputEventQueuer::readch::h76b22a78ba7942fd
  17:        0x10431221c - fish::input::<impl fish::reader::Reader>::read_char::h450a4c437c897756
  18:        0x1043217c0 - fish::reader::Reader::handle_char_event::hdb13cb5324d3def7
  19:        0x10431f718 - fish::reader::Reader::readline::h4cdd3d049dc0f85a
  20:        0x10431ca30 - fish::reader::reader_read::h7e4a159b9e5ba63e
  21:        0x104186560 - fish::throwing_main::h4fb6c567e629eccd
  22:        0x104358e44 - fish::panic::panic_handler::h4f4283554d43e2bd
  23:        0x104182074 - fish::main::h4f18d10676f87194
  24:        0x104358710 - std::sys::backtrace::__rust_begin_short_backtrace::ha86d437732954b75
  25:        0x1041895e8 - _main
fish crashed, please report a bug. Debug PID 78250 or press Enter to exit
```

So, it somehow seems to be related to configuration, but I can't tell quite how.

**Comment by lgarron** [comment]
Okay, I managed to dig in enough to figure out that this is uniquely caused by the presence of `/opt/homebrew/bin` in `fish_user_paths` in `~/.config/fish/fish_variables`.

So it seems that some binary in my path is crashing the character rendering width calculations. I'm not sure how to debug from here.

**Comment by lgarron** [comment]
> Okay, I managed to dig in enough to figure out that this is uniquely caused by the presence of `/opt/homebrew/bin` in `fish_user_paths` in `~/.config/fish/fish_variables`.

Okay, I managed to figure out further that it's due to the specific presence of `/opt/homebrew/bin/hevc`. This is a symlink to a Homebrew installation of: https://github.com/lgarron/scripts/blob/c7b74a9da4ef4eec8409a5f8b8c361c64fba6412/video/hevc.ts

So the repro should be:

```
brew install --HEAD lgarron/lgarron/hevc
```

I am at a loss as to which the presence of this symlink would cause the crash in question.

**Comment by lgarron** [comment]
@krobelus: Thanks, I can confirm that the fix works for me! 🤩
