### ISSUE TITLE
Cannot use fish_config prompt editor with python3.4 on Archlinux

### ISSUE THREAD

**Issue by StatelessCat** [fish-shell/fish-shell#2040]
Hey fishes :)
This happend when I try to edit the prompt using fish_config: 
```
$$ fish_config
Web config started at 'file:///home/<MYUSERHERE>/.cache/fish/web_config-WQABKO.html'. Hit enter to stop.

(process:4472): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(firefox:4472): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
----------------------------------------
Exception happened during processing of request from ('::1', 46350, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.4/socketserver.py", line 673, in __init__
    self.handle()
  File "/usr/lib/python3.4/http/server.py", line 398, in handle
    self.handle_one_request()
  File "/usr/lib/python3.4/http/server.py", line 386, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 520, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 468, in do_get_sample_prompts_list
    result.append(self.read_one_sample_prompt(fd))
  File "/usr/share/fish/tools/web_config/webconfig.py", line 448, in read_one_sample_prompt
    for line in fd:
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 617: ordinal not in range(128)
----------------------------------------
```
```
VERSIONS:
fish 2.1.2-1
python 3.4.3-2
```

Do you know any workaround to launch this script using a supported version of python ? 
Thanks

**Comment by zanchey** [comment]
Which prompt were you trying to select?

This code is much better in the development version of fish, so hopefully this problem will not be around for much longer.

**Comment by StatelessCat** [comment]
I'm not selecting any prompt, just click on the tab "prompt" : http://i.imgur.com/9NVNhqE.png .

**Comment by zanchey** [comment]
In that case, I think the error is probably being produced by trying to render your current prompt. Does your username have an â in it, by any chance?

If not, could you paste the output of `functions fish_prompt` and also `fish_prompt | xxd`?

**Comment by ridiculousfish** [comment]
It's dying on this line:

    for line in fd:

where fd is something we get from open(), which ought to default to UTF-8. But here we're getting the ASCII code, which suggests something is screwy with your locale.

What are your values for `$LANG` and `$LC_ALL`?

**Comment by StatelessCat** [comment]
Hey, sorry for the late response.
Thanks both of you for your help.

## @zanchey 
### The output of ```functions fish_prompt```: 
```
function fish_prompt
   set_color green
   printf '%s' (whoami)
   set_color normal
   printf ' at '

   set_color green
   printf '%s' (hostname|cut -d . -f 1)
   set_color normal
   printf ' in '

   set_color $fish_color_cwd
   printf '%s' (prompt_pwd)
   set_color normal

   # Line 2
   echo
   if test $VIRTUAL_ENV
       printf "(%s) " (set_color blue)(basename $VIRTUAL_ENV)(set_color normal)
   end
   printf '_'
   set_color normal
end
```
### ```fish_prompt | xxd``` : 
```
00000000: 1b5b 3332 6d72 6170 6861 656c 1b5b 3330  .[32mraphael.[30
00000010: 6d1b 2842 1b5b 6d20 6174 201b 5b33 326d  m.(B.[m at .[32m
00000020: 7263 6c2d 6465 736b 2d61 7263 681b 5b33  rcl-desk-arch.[3
00000030: 306d 1b28 421b 5b6d 2069 6e20 1b5b 3332  0m.(B.[m in .[32
00000040: 6d7e 1b5b 3330 6d1b 2842 1b5b 6d0a 5f1b  m~.[30m.(B.[m._.
00000050: 5b33 306d 1b28 421b 5b6d                            [30m.(B.[m
```
## @ridiculousfish 
I'm using ```LANG = fr_FR.UTF-8``` and ``` LC_ALL = ``` (empty), and if i set ``` LC_ALL = fr_FR.UTF-8```, i got the same issue. 
I have tried ```en_EN.UTF-8``` for both ```LANG``` and ```LC_ALL```, i still got 
``` 
Web config started at 'file:///home/raphael/.cache/fish/web_config-PSW3UO.html'. Hit enter to stop.

(process:5613): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(firefox:5613): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
----------------------------------------
Exception happened during processing of request from ('::1', 43480, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.4/socketserver.py", line 673, in __init__
    self.handle()
  File "/usr/lib/python3.4/http/server.py", line 398, in handle
    self.handle_one_request()
  File "/usr/lib/python3.4/http/server.py", line 386, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 520, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 468, in do_get_sample_prompts_list
    result.append(self.read_one_sample_prompt(fd))
  File "/usr/share/fish/tools/web_config/webconfig.py", line 448, in read_one_sample_prompt
    for line in fd:
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 617: ordinal not in range(128)
----------------------------------------
```

**Comment by zanchey** [comment]
> (firefox:4472): Gtk-WARNING **: Locale not supported by C library.
>         Using the fallback 'C' locale.

This is in both your pastes and is a bit suspicious. Do you need to regenerate the locale or something? I'm not hugely familiar with Arch but https://wiki.archlinux.org/index.php/Locale looks helpful.

**Comment by StatelessCat** [comment]
Thanks for your help and patience. 

In KDE plasma5 settings I was setting the French language. This lead to an override of locales. I set it to en_US.UTF-8 like the Archlinux global locale configuration and now everything works :)

**Comment by zanchey** [comment]
Glad it's fixed!
