### ISSUE TITLE
fish_update_completions locale issues

### ISSUE THREAD

**Issue by icf20** [fish-shell/fish-shell#3500]
```
fish_update_completions
manpath: can't set the locale; make sure $LC_* and $LANG are correct
Traceback (most recent call last):
  File "/usr/share/fish/tools/create_manpage_completions.py", line 973, in <module>
    cleanup_autogenerated_completions_in_directory(output_directory)
  File "/usr/share/fish/tools/create_manpage_completions.py", line 693, in cleanup_autogenerated_completions_in_directory
    cleanup_autogenerated_file(path)
  File "/usr/share/fish/tools/create_manpage_completions.py", line 701, in cleanup_autogenerated_file
    if file_is_overwritable(path):
  File "/usr/share/fish/tools/create_manpage_completions.py", line 668, in file_is_overwritable
    for line in file:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 233: ordinal not in range(128)
```

```
$ fish -v
fish, version 2.3.1
```

etc/locale.conf

```
LANG=es_ES.UTF-8
LC_COLLATE=es_ES.UTF-8
```

**Comment by faho** [comment]
For 2.3.1, locale.conf is irrelevant. We do not read that file in that version.

Can you confirm that `locale` prints "LANG=C"? If so, this has been fixed by reading locale.conf in 2.4b1.

**Comment by faho** [comment]
@icf20: Ping?

**Comment by krader1961** [comment]
@icf20: Ping?

**Comment by faho** [comment]
@icf20: I'm closing this for now. If you ever get around to it, please comment and we'll reopen!
