### ISSUE TITLE
fish_config crashes on switch to "abbreviations" tab

### ISSUE THREAD

**Issue by enedil** [fish-shell/fish-shell#4098]
```
enedil@lisbook ~> fish --version
fish, version 2.3.1
enedil@lisbook ~> uname -a
Linux lisbook 4.10.17-200.fc25.x86_64 #1 SMP Mon May 22 18:12:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
enedil@lisbook ~> lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 25 (Twenty Five)
Release:	25
Codename:	TwentyFive
```

When I run `fish_config` and then in the browser, I switch to "abbreviations" tab, server crashes with following backtrace:
```
enedil@lisbook ~> fish_config 
Web config started at 'file:///home/enedil/.cache/fish/web_config-VSEG9L.html'. Hit enter to stop.
----------------------------------------
Exception happened during processing of request from ('::1', 42130, 0, 0)
Traceback (most recent call last):
  File "/usr/lib64/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib64/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 776, in do_GET
    output = self.do_get_abbreviations()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in do_get_abbreviations
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in <listcomp>
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
ValueError: not enough values to unpack (expected 2, got 1)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 42132, 0, 0)
Traceback (most recent call last):
  File "/usr/lib64/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib64/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 776, in do_GET
    output = self.do_get_abbreviations()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in do_get_abbreviations
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in <listcomp>
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
ValueError: not enough values to unpack (expected 2, got 1)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 42134, 0, 0)
Traceback (most recent call last):
  File "/usr/lib64/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib64/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 776, in do_GET
    output = self.do_get_abbreviations()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in do_get_abbreviations
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in <listcomp>
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
ValueError: not enough values to unpack (expected 2, got 1)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 42136, 0, 0)
Traceback (most recent call last):
  File "/usr/lib64/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib64/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 776, in do_GET
    output = self.do_get_abbreviations()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in do_get_abbreviations
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in <listcomp>
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
ValueError: not enough values to unpack (expected 2, got 1)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 42138, 0, 0)
Traceback (most recent call last):
  File "/usr/lib64/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib64/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 776, in do_GET
    output = self.do_get_abbreviations()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in do_get_abbreviations
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in <listcomp>
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
ValueError: not enough values to unpack (expected 2, got 1)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 42140, 0, 0)
Traceback (most recent call last):
  File "/usr/lib64/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib64/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 776, in do_GET
    output = self.do_get_abbreviations()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in do_get_abbreviations
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in <listcomp>
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
ValueError: not enough values to unpack (expected 2, got 1)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 42142, 0, 0)
Traceback (most recent call last):
  File "/usr/lib64/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib64/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 776, in do_GET
    output = self.do_get_abbreviations()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in do_get_abbreviations
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in <listcomp>
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
ValueError: not enough values to unpack (expected 2, got 1)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 42144, 0, 0)
Traceback (most recent call last):
  File "/usr/lib64/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib64/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 776, in do_GET
    output = self.do_get_abbreviations()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in do_get_abbreviations
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in <listcomp>
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
ValueError: not enough values to unpack (expected 2, got 1)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 42146, 0, 0)
Traceback (most recent call last):
  File "/usr/lib64/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib64/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 776, in do_GET
    output = self.do_get_abbreviations()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in do_get_abbreviations
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in <listcomp>
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
ValueError: not enough values to unpack (expected 2, got 1)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 42148, 0, 0)
Traceback (most recent call last):
  File "/usr/lib64/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib64/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 776, in do_GET
    output = self.do_get_abbreviations()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in do_get_abbreviations
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
  File "/usr/share/fish/tools/web_config/webconfig.py", line 709, in <listcomp>
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
ValueError: not enough values to unpack (expected 2, got 1)
----------------------------------------
```

As advised, in the issue template, I ran `fish` with tmp home directory, and the issue does not happen anymore. May it be some kind of overridden module versions for Python?

**Comment by krader1961** [comment]
When you run fish with a temp home directory you're excluding all of your personal customizations including your abbreviations. So it's not surprising you don't see a problem when you do that.

What does `abbr` output? What does `printf '|%s|\n' $fish_user_abbreviations` output? There have been several bug fixes to `fish_config` since the 2.3.1 release. Can you try a newer fish?

**Comment by enedil** [comment]
@krader1961 `abbr` is clear, so is the second command. I haven't defined any abbreviations so far.

I might upgrade, fish 2.3.1 is the latest in Fedora repos though (it might not be true in Fedora 26, which is still alpha).

**Comment by krader1961** [comment]
If you have no abbreviations it should be impossible to observe the failure you reported. I'm willing to bet you have something in your *config.fish* that is writing to stdout when the shell is not interactive. Does `fish -c 'echo done'` output anything other than the word "done"?

**Comment by enedil** [comment]
Only outputs `done`. I have a command in my `config.fish` that may cause the bug and it is writing to console - it's an app that changes the color of my terminal according to wallpaper. Indeed, commenting it out removes the bug. How exactly writing directly to terminal affects `fish_config` and is there any way to circumvent the issue?

**Comment by krader1961** [comment]
You should never, ever, run anything in your *config.fish* init script that will write to stdout or stderr if the session is not interactive. Doing so will break not just `fish_config` but also attempts to `ssh` to your machine or use fish in many other non-interactive ways. The way to protect against this is to predicate running such commands on the shell being interactive:

```
if status is-interactive
   echo hello
end
```
