### ISSUE TITLE
Running `ls` inside fish shell generates weird error messages

### ISSUE THREAD

**Issue by topecongiro** [fish-shell/fish-shell#4361]
I just installed fish-shell via `yaourt -S fish` on Arch Linux, and it give very weird error messages when I run `ls`:
```
module.js:491
    throw err;
    ^

Error: Cannot find module '../test/runcases'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/uchida/.local/bin/test:5:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```
The outcome is identical when I tried `sh -c 'env HOME=$(mktemp -d) fish'`.

## Env
* `fish --version`: 2.6.0
* `uname -a`: `Linux uchida 4.12.8-2-ARCH #1 SMP PREEMPT Fri Aug 18 14:08:02 UTC 2017 x86_64 GNU/Linux`
* `echo $TERM`: `xterm-256color`

**Comment by zanchey** [comment]
The problem is that you have a command called `test` in your path (`.local/bin/test`), which fish expects to be the POSIX test utility. Removing or renaming this script should yield the behaviour you expect.

It's required because the fish builtin `test` doesn't work properly with regular file descriptors. See #1228.

**Comment by topecongiro** [comment]
@zanchey Thank you for the reply! It solved my problem.
