### ISSUE TITLE
fish_config has no attribute 'path' error

### ISSUE THREAD

**Issue by gavinhow** [fish-shell/fish-shell#4968]
fish, version 2.7.1
Mac 10.13.4
Terminal

Having a problem using fish_config. When I run `fish_config` it opens a browser which then throws the following error.

```----------------------------------------
Exception happened during processing of request from ('::1', 49723, 0, 0)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 320, in handle_one_request
    if not self.parse_request():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 281, in parse_request
    "Bad HTTP/0.9 request type (%r)" % command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 364, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/local/Cellar/fish/2.7.1/share/fish/tools/web_config/webconfig.py", line 1020, in log_error
    args = (code, msg, self.path)
AttributeError: FishConfigHTTPRequestHandler instance has no attribute 'path'
----------------------------------------
```

I tried completely reinstalling fish and it didn't seem to help.

Thanks

**Comment by faho** [comment]
The "path" bit here is a red herring - that is an error that happens while trying to log another error.

I can reproduce that "Bad HTTP/0.9 request type" if I request the page over http**s** - do you perhaps have some browser addon that changes all requests to https? If so, this is not https. It's a purely local http connection.

**Comment by faho** [comment]
No info in quite a while, closing. If anyone can reproduce this, please speak up and we'll reopen!
