### ISSUE TITLE
pip hangs when using fish-shell

### ISSUE THREAD

**Issue by the0demiurge** [fish-shell/fish-shell#5040]
fish, version 2.7.1
Linux Laptop 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux
xterm-256color
```
Welcome to fish, the friendly interactive shell
charles@Laptop /h/charles> pip iTraceback (most recent call last):
  File "/home/charles/anaconda3/bin/pip", line 4, in <module>
    import pip
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/__init__.py", line 43, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3031, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 651, in _build_master
    ws = cls()
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2024, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2433, in from_location
    py_version=py_version, platform=platform, **kw
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2773, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2398, in _version_from_file
    line = next(iter(version_lines), '')
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2565, in _get_metadata
    if self.has_metadata(name):
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/home/charles/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1565, in _has
    return os.path.exists(path)
  File "/home/charles/anaconda3/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
KeyboardInterrupt
```
It shows that pip importing python module takes a long time, which makes the command line completely hangs, and this makes it impossible to type any character except wait for while or sending keyboard interrupt.

This may be reproduced everytime you use pip in a new terminal, please fix this, thanks :)

**Comment by krader1961** [comment]
Works for me. I use pip all the time including the Anaconda version (I've got nine Anaconda managed python environments) in addition to the system python pip. The probability your problem has anything to do with fish is pretty small. Note that it is apparently hung doing `os.stat(path)`. The first thing that suggests to me is a slow or hung filesystem. Try adding a diagnostic print to that function to see which path is causing the problem. Then see what happens if you use the usual unix tools, e.g., `ls -l` and `cat`, to examine the path.

**Comment by faho** [comment]
@the0demiurge: This looks like you haven't executed a `pip` command yet?

I.e. the issue appears when you type `pip i`, but before you've pressed enter.

If so, it's happening when fish loads the `pip` completion script (which happens even if you don't explicitly try completing anything).

That entire script currently looks like

```fish
if command -sq pip
    pip completion --fish 2>/dev/null | source
end
```

So it executes `pip completion --fish`. I suggest you see how long that takes on your system - it's been known to take about 0.5s.

We've had discussions about this in https://github.com/fish-shell/fish-shell/pull/4448 - we probably want to just commit that output.

**Comment by faho** [comment]
>My walkaround is removing fish-completion of pip, would there be a better solution?

There's a variety of things to do:

- Put the output of `pip completion --fish` into the completion script directly - this would remove the slowdown when not explicitly completing.

- Rewrite the entire script in fish, without invoking pip - this _should_ be quite fast (tens of milliseconds), and any python tool is going to slow it down

- Make pip fast

The third is my favorite, because that would help everyone, and there seems to be quite some room for improvement. The case of `pip completion` is annoying - why does that care about the number of packages? - but even a simple `pip --version` with a clean install takes 400ms.

However, that's work for the pip people (piple?), and if we had this in fish script, we could add descriptions and such.

**Comment by krader1961** [comment]
I didn't realize you were using pip completions (something I've never used). Just installing the completion support, i.e., running `/usr/local/bin/pip3 completion --fish`, takes 600 ms on my one year old Macbook Pro and my top of the line Mac Pro server -- both having SSD drives. Actually completing an installed package name with ~50 installed packages takes ~200 ms. As @faho points out this isn't fish's fault. The `pip` command is slow.

**Comment by the0demiurge** [comment]
Thanks, I'll try to find a way to make pip faster :)
