### ISSUE TITLE
Broke fish_config.

### ISSUE THREAD

**Issue by Randomneo** [fish-shell/fish-shell#5058]
I don't know what cause the problem. I mostly think that I did something wrong, but I don't know how to fix this. Im using archlinux.
In prompt tab i got [tnis](https://snag.gy/CEFuLa.jpg)
Other tab also broken.
When i try get to abbreviations tap. I got this error in my terminal
```
----------------------------------------
Exception happened during processing of request from ('::1', 35326, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 919, in do_GET
    output = self.do_get_abbreviations()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 843, in do_get_abbreviations
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
  File "/usr/share/fish/tools/web_config/webconfig.py", line 843, in <listcomp>
    result = [{'word': x, 'phrase': y} for x, y in abbrs]
ValueError: not enough values to unpack (expected 2, got 1)
----------------------------------------

```
```
$ fish -version
fish, version 2.7.1

$ echo $TERM
rxvt-unicode-256color
```

**Comment by faho** [comment]
@Randomneo: Please check that your configuration does not print anything when fish is not interactive. This includes things like `clear`, which work by printing escape sequences that your terminal then interprets, some of which you're getting in the prompt tab.

**Comment by Randomneo** [comment]
Oh. Thank you. I got neofetch on starting. Is there some workaround to not disable my neofetch output?

**Comment by faho** [comment]
>Is there some workaround to not disable my neofetch output?

You only have to disable it if fish isn't interactive.

So either use 

```fish
if status is-interactive
    neofetch
end
```

in config.fish, or put it inside your `fish_greeting` function.
