### ISSUE TITLE
fish_config DeprecationWarning & cgi.escape and broken pipe

### ISSUE THREAD

**Issue by mustafawm** [fish-shell/fish-shell#5125]
version 2.6.0
macOS High Sierra 
iTerm2 

when running `fish_config` 

### without 3rd party plugins 
The following warning is thrown: 
```
/usr/local/share/fish/tools/web_config/webconfig.py:307: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  result.append(cgi.escape(strip_ansi(component)))
```

### with plugins enabled and all, same warning plus the below error after slow navigation/refreshing
```
Exception happened during processing of request from ('::1', 51023, 0, 0)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 344, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/share/fish/tools/web_config/webconfig.py", line 919, in do_GET
    self.write_to_wfile('\n')
  File "/usr/local/share/fish/tools/web_config/webconfig.py", line 543, in write_to_wfile
    self.wfile.write(txt.encode('utf-8'))
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py", line 796, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by mananpreetsingh** [comment]
I have the same issue:
MAC OS: 10.13.6
Fish, version 2.7.1
iTerm2 Build 3.2.0

**Comment by mqudsi** [comment]
@zanchey `html.escape` is python 3.2+, can we use it as-is or do we need to to special case this?

ref https://wiki.python.org/moin/EscapingHtml

**Comment by zanchey** [comment]
That should be fine, although I think it needs to stay as `cgi.escape` under Python 2.
