### ISSUE TITLE
`read -z` needs better error handling on overflow

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5290]
A repro courtesy of my new best friend for overflows, `all-the-package-names`:

```fish
mqudsi@ZBook /m/c/U/m/r/fish-shell> all-the-package-names  | read -zl overflow
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
```

[and _my_ is `read` slow](https://github.com/fish-shell/fish-shell/issues/4972)

**Comment by zanchey** [comment]
Hang on, isn't that error coming from all-the-package-names?

**Comment by mqudsi** [comment]
Yes, but only because fish decided there was too much data and closed the buffer. Fish doesn’t provide any notice about having done so, so to someone not intimately familiar with fish it would seem there’s a problem with the application being run and not the script or the shell running it.
