### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by TimWolla** [fish-shell/fish-shell#6037]
```
[timwolla@~]fish --version
fish, version 3.0.2-1435-gab6fd655
[timwolla@~]echo $version
3.0.2-1435-gab6fd655
[timwolla@~]uname -a
Linux *snip* 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[timwolla@~]echo $TERM
xterm-256color
```
= Bleeding edge fish on gnome-terminal on Ubuntu 16.04

When writing a `for` loop and a line exceeds the width of the terminal fish crashes:

![fish](https://user-images.githubusercontent.com/209270/62778988-2ccba780-bab2-11e9-841a-3422f9712442.gif)

Note: It is necessary that the `end` keyword already exists. Without it fish does not crash.

```
(gdb) bt full
#0  0x00007ffff6d6d428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 8876
        selftid = 8876
#1  0x00007ffff6d6f02a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 13 times>, 9165616, 140737334945819, 9168504}}, sa_flags = -143964032, sa_restorer = 0x8be678}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff76b784d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff76b56b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff76b5701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff76b5919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff76de3f7 in std::__throw_out_of_range_fmt(char const*, ...) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x00000000005156cf in ?? ()
No symbol table info available.
#8  0x0000000000517025 in s_write(screen_t*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, unsigned long, std::vector<highlight_spec_t, std::allocator<highlight_spec_t> > const&, std::vector<int, std::allocator<int> > const&, unsigned long, page_rendering_t const&, bool) ()
No symbol table info available.
#9  0x0000000000507d4b in reader_data_t::repaint() ()
No symbol table info available.
#10 0x000000000050a5d8 in reader_data_t::insert_string(editable_line_t*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&) ()
No symbol table info available.
#11 0x0000000000510aaf in reader_data_t::readline[abi:cxx11](int) ()
No symbol table info available.
#12 0x00000000005110dd in reader_read(parser_t&, int, io_chain_t const&) ()
No symbol table info available.
#13 0x000000000044704a in main ()
No symbol table info available.
```

**Comment by zanchey** [comment]
Nice find. With symbols enabled, this looks like:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f0406f4442a in __GI_abort () at abort.c:89
#2  0x00007f0407a780ad in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f0407a76066 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f0407a760b1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f0407a762c9 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f0407a9eb85 in std::__throw_out_of_range_fmt(char const*, ...) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x000055874a5f210b in std::vector<line_t, std::allocator<line_t> >::_M_range_check (__n=<optimized out>,
    this=<optimized out>) at /usr/include/c++/6/bits/stl_vector.h:804
#8  std::vector<line_t, std::allocator<line_t> >::at (__n=<optimized out>, this=<optimized out>)
    at /usr/include/c++/6/bits/stl_vector.h:825
#9  screen_data_t::line (idx=<optimized out>, this=<optimized out>) at src/screen.h:101
#10 s_desired_append_char (s=s@entry=0x55874b5f1980, b=<optimized out>, c=..., indent=<optimized out>,
    prompt_width=prompt_width@entry=19, bwidth=<optimized out>) at src/screen.cpp:422
#11 0x000055874a5f3ac3 in s_write (s=s@entry=0x55874b5f1980,
    left_prompt=L"\033[1m\033[32mzanchey\033[m\017@\033[1m\033[36mmotsugo\033[m\017 \033[32m~\033[m\017\033[m\017> ",
    right_prompt=L"",
    commandline=L"for i in alksdjfkjlkjasdlfkjsklfjakldsfjaskdjfskdjfskdfjlsdkjfiurqoiewurioqweuriqweurioeurdfkjdfkjdkfjdkfjdkjf\nend", explicit_len=explicit_len@entry=114, colors=std::vector of length 114, capacity 114 = {...},
    indent=std::vector of length 114, capacity 114 = {...}, cursor_pos=110, pager=..., cursor_is_within_pager=false)
    at src/screen.cpp:1060
#12 0x000055874a5e7156 in reader_data_t::repaint (this=this@entry=0x55874b5f17e0)
    at src/reader.cpp:645
#13 0x000055874a5e98e8 in reader_data_t::insert_string (this=0x55874b5f17e0, el=0x55874b5f1800, str=...)
    at src/reader.cpp:1125
#14 0x000055874a5ed624 in reader_data_t::insert_char (c=<optimized out>, el=<optimized out>, this=0x55874b5f17e0)
    at src/reader.cpp:445
#15 reader_data_t::readline[abi:cxx11](int) (this=0x55874b5f17e0, nchars_or_0=nchars_or_0@entry=0)
    at src/reader.cpp:3283
#16 0x000055874a5edc38 in reader_readline[abi:cxx11](int) (nchars=0) at src/reader.cpp:3365
#17 read_i (parser=...) at src/reader.cpp:2263
#18 reader_read (parser=..., fd=<optimized out>, io=...) at src/reader.cpp:3563
#19 0x000055874a51b789 in main (argc=<optimized out>, argv=0x7ffcd8714d18)
    at src/fish.cpp:492
```

**Comment by ridiculousfish** [comment]
Nice! Thanks for taking the time to report this!
