### ISSUE TITLE
Prompt TAB doesn't work

### ISSUE THREAD

**Issue by Penultimate70** [fish-shell/fish-shell#7143]
fish, version 3.1.2

OS: macOS Catalina 10.15.5 19F101 x86_64
Terminal: iTerm2

I've installed fish using Homebrew.
I have not installed any 3-rd party extras.

When i enter the configuration web pages "fish_config" in the default browser, Safari, and access the "PROMPT" tab no prompts show and I get an error in fish as well as in the browser.

FISH ERROR:
```
Exception happened during processing of request from ('::ffff:127.0.0.1', 55132, 0, 0)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 344, in process_request
    self.finish_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 415, in handle
    self.handle_one_request()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 403, in handle_one_request
    method()
  File "/usr/local/Cellar/fish/3.1.2/share/fish/tools/web_config/webconfig.py", line 1262, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/usr/local/Cellar/fish/3.1.2/share/fish/tools/web_config/webconfig.py", line 1169, in do_get_sample_prompts_list
    sample_results = pool.map(self.read_one_sample_prompt, paths, 1)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/Cellar/fish/3.1.2/share/fish/tools/web_config/webconfig.py", line 1155, in read_one_sample_prompt
    result = self.do_get_sample_prompt(func, extras_dict)
  File "/usr/local/Cellar/fish/3.1.2/share/fish/tools/web_config/webconfig.py", line 1116, in do_get_sample_prompt
    return self.do_get_prompt(cmd, text.strip(), extras_dict)
  File "/usr/local/Cellar/fish/3.1.2/share/fish/tools/web_config/webconfig.py", line 1088, in do_get_prompt
    prompt_demo_ansi, err = run_fish_cmd(command_to_run)
  File "/usr/local/Cellar/fish/3.1.2/share/fish/tools/web_config/webconfig.py", line 86, in run_fish_cmd
    print("$ " + text)
UnicodeEncodeError: 'ascii' codec can't encode character '\u27a4' in position 535: ordinal not in range(128)
```

SAFARI Error Message
`The request received an error. Perhaps the server has shut down.`

Thanks
Mike

**Comment by faho** [comment]
Yeah, your python is trying to use ascii. Ordinarily this means your locale is set to a (broken) "C" value.

In this case we take special care to try to set the locale to something that can do utf-8, but there is no actual value that is guaranteed to be supported so we can only try `en_US.UTF-8`.

Please give the output of `locale`.

**Comment by Penultimate70** [comment]
Here is what I see...
/ >locale
LANG="en_US.US-ASCII"
LC_COLLATE="en_US.US-ASCII"
LC_CTYPE="en_US.US-ASCII"
LC_MESSAGES="en_US.US-ASCII"
LC_MONETARY="en_US.US-ASCII"
LC_NUMERIC="en_US.US-ASCII"
LC_TIME="en_US.US-ASCII"
LC_ALL=

**Comment by faho** [comment]
Yeah, that locale can't handle UTF-8 inputs.

You need to change it.

**Comment by Penultimate70** [comment]
Well that was easy. Thank you.
