### ISSUE TITLE
fish_update_completions error

### ISSUE THREAD

**Issue by LiEyWe** [fish-shell/fish-shell#7242]
fish version: 3.1.2
terminal: xterm-256color
OS: Arch Linux
Kernel: Linux 5.4.55-1-lts
Architecture: x86-64

Steps to reproduce:
1 - run `fish`
2 - run `fish_update_completions`
3 - get this error:

`Traceback (most recent call last):
  File "/usr/share/fish/tools/create_manpage_completions.py", line 1066, in <module>
    file_paths.extend(get_paths_from_man_locations())
  File "/usr/share/fish/tools/create_manpage_completions.py", line 965, in get_paths_from_man_locations
    manpath, err_data = proc.communicate()
AttributeError: 'NoneType' object has no attribute 'communicate'`

**Comment by LiEyWe** [comment]
The problem was that I did not install man-db an man-pages
