### ISSUE TITLE
Fish, Python subprocess.run(), and SIGINT interaction

### ISSUE THREAD

**Issue by guy-middleton** [fish-shell/fish-shell#7247]
I encountered this problem using the helpful [vex](https://pypi.org/project/vex/) utility for Python virtualenvs. When run from vex, fish does not catch a CTRL-C keyboard interrupt, which then terminates the shell. 

The problem is not specific to vex, we can reproduce using Python's subprocess.run() as follows:

```
% python
Python 3.8.5 (default, Jul 21 2020, 10:42:08)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.run("fish")
macbook> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 491, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1016, in communicate
    self.wait()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1079, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1804, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1762, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
>>>
% 
```

None of the other shells I tried (bash, ksh, zsh) have this behaviour.

This appears to be caused by fish not creating a process group, as discussed in https://github.com/fish-shell/fish-shell/issues/7060#issuecomment-636421938.

Fish 3.1.2, also tried latest source (commit f7ef91ae2)
MacOS Mojave 10.14.6; Darwin Kernel Version 18.7.0
Iterm2 Build 3.3.12

**Comment by zanchey** [comment]
See also #5909, which is the same problem but `fish --interactive` will work now.

**Comment by ridiculousfish** [comment]
I added the check for `--interactive` because it seemed like a good idea at the time, but I didn't have any real reason and probably we should match other shells here.

**Comment by guy-middleton** [comment]
I'm not sure which would be more correct -- to fix the problem in fish or in vex. The vex fix is simple, just pass `--interactive` if the shell is fish and is called with no arguments.
