### ISSUE TITLE
fish_config doesn't load prompt page in Termux

### ISSUE THREAD

**Issue by phantom2152** [fish-shell/fish-shell#7298]
Fish version
fish, version 3.1.2

Operating system
Linux localhost 4.9.179-perf+ #1 SMP PREEMPT Fri Jul 17 19:30:50 CST 2020 aarch64 Android

  sh -c 'env HOME=$(mktemp -d) fish'
Does not affect the behaviour I am reporting

When I give the command fish_config and open the prompt tab in browser I get an error saying "The request received an error. Perhaps the server has shut down
![Screenshot_20200831-162152](https://user-images.githubusercontent.com/70034285/91713328-17239700-eb79-11ea-9513-a5d1ba22ef1d.jpg)

Also I get these error message on the terminal

u0_a1025@localhost /d/d/c/f/home> fish_config
Web config started at file:///data/data/com.termux/files/usr/tmp/web_config0mlwjt5f.html
Hit ENTER to stop.
$ set -L
----------------------------------------
Exception happened during processing of request from ('::ffff:127.0.0.1', 46052, 0, 0)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1262, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1162, in do_get_sample_prompts_list
    pool = multiprocessing.pool.ThreadPool(processes=8)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::ffff:127.0.0.1', 46054, 0, 0)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1262, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1162, in do_get_sample_prompts_list
    pool = multiprocessing.pool.ThreadPool(processes=8)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::ffff:127.0.0.1', 46056, 0, 0)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1262, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1162, in do_get_sample_prompts_list
    pool = multiprocessing.pool.ThreadPool(processes=8)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::ffff:127.0.0.1', 46058, 0, 0)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1262, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1162, in do_get_sample_prompts_list
    pool = multiprocessing.pool.ThreadPool(processes=8)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::ffff:127.0.0.1', 46060, 0, 0)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1262, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1162, in do_get_sample_prompts_list
    pool = multiprocessing.pool.ThreadPool(processes=8)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::ffff:127.0.0.1', 46062, 0, 0)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1262, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1162, in do_get_sample_prompts_list
    pool = multiprocessing.pool.ThreadPool(processes=8)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::ffff:127.0.0.1', 46064, 0, 0)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1262, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1162, in do_get_sample_prompts_list
    pool = multiprocessing.pool.ThreadPool(processes=8)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::ffff:127.0.0.1', 46066, 0, 0)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1262, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1162, in do_get_sample_prompts_list
    pool = multiprocessing.pool.ThreadPool(processes=8)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::ffff:127.0.0.1', 46068, 0, 0)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1262, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1162, in do_get_sample_prompts_list
    pool = multiprocessing.pool.ThreadPool(processes=8)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::ffff:127.0.0.1', 46070, 0, 0)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/data/data/com.termux/files/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1262, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/data/data/com.termux/files/usr/share/fish/tools/web_config/webconfig.py", line 1162, in do_get_sample_prompts_list
    pool = multiprocessing.pool.ThreadPool(processes=8)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

**Comment by faho** [comment]
Yup, see https://github.com/termux/termux-packages/issues/570.

Fortunately, we can just resort to running these one after the other, and with the current set that should only take a few seconds.

If we ever add more (especially slower) prompts this may become annoying, but there's nothing we can do about it.
