### ISSUE TITLE
Error with fish_config

### ISSUE THREAD

**Issue by DmitryevichD** [fish-shell/fish-shell#7917]
fish, version 3.2.2
Ubuntu 20.04
Terminal

Can't start fish_config

```Web config started at file:///tmp/web_confignr46u8qe.html
Hit ENTER to stop.
----------------------------------------
Exception happened during processing of request from ('::1', 58062, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.8/http/server.py", line 294, in parse_request
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 405, in handle_one_request
    if not self.parse_request():
  File "/usr/lib/python3.8/http/server.py", line 307, in parse_request
    self.send_error(
  File "/usr/lib/python3.8/http/server.py", line 457, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/share/fish/tools/web_config/webconfig.py", line 1438, in log_error
    args = (code, msg, self.path)
AttributeError: 'FishConfigHTTPRequestHandler' object has no attribute 'path'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 58064, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.8/http/server.py", line 294, in parse_request
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 405, in handle_one_request
    if not self.parse_request():
  File "/usr/lib/python3.8/http/server.py", line 307, in parse_request
    self.send_error(
  File "/usr/lib/python3.8/http/server.py", line 457, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/share/fish/tools/web_config/webconfig.py", line 1438, in log_error
    args = (code, msg, self.path)
AttributeError: 'FishConfigHTTPRequestHandler' object has no attribute 'path'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 58066, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.8/http/server.py", line 294, in parse_request
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 405, in handle_one_request
    if not self.parse_request():
  File "/usr/lib/python3.8/http/server.py", line 307, in parse_request
    self.send_error(
  File "/usr/lib/python3.8/http/server.py", line 457, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/share/fish/tools/web_config/webconfig.py", line 1438, in log_error
    args = (code, msg, self.path)
AttributeError: 'FishConfigHTTPRequestHandler' object has no attribute 'path'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 58068, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.8/http/server.py", line 294, in parse_request
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 405, in handle_one_request
    if not self.parse_request():
  File "/usr/lib/python3.8/http/server.py", line 307, in parse_request
    self.send_error(
  File "/usr/lib/python3.8/http/server.py", line 457, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/share/fish/tools/web_config/webconfig.py", line 1438, in log_error
    args = (code, msg, self.path)
AttributeError: 'FishConfigHTTPRequestHandler' object has no attribute 'path'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 58076, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.8/http/server.py", line 294, in parse_request
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 405, in handle_one_request
    if not self.parse_request():
  File "/usr/lib/python3.8/http/server.py", line 307, in parse_request
    self.send_error(
  File "/usr/lib/python3.8/http/server.py", line 457, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/share/fish/tools/web_config/webconfig.py", line 1438, in log_error
    args = (code, msg, self.path)
AttributeError: 'FishConfigHTTPRequestHandler' object has no attribute 'path'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('::1', 58078, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python3.8/http/server.py", line 294, in parse_request
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 405, in handle_one_request
    if not self.parse_request():
  File "/usr/lib/python3.8/http/server.py", line 307, in parse_request
    self.send_error(
  File "/usr/lib/python3.8/http/server.py", line 457, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/share/fish/tools/web_config/webconfig.py", line 1438, in log_error
    args = (code, msg, self.path)
AttributeError: 'FishConfigHTTPRequestHandler' object has no attribute 'path'
----------------------------------------

```

**Comment by DmitryevichD** [comment]
My browser is opened the fish_configs link by HTTPS, but if I change it  to HTTP - config work correctly

**Comment by faho** [comment]
Ah, okay. You have one of those addons that switches http to https. That won't work, as we don't have any certificates etc in play here. This is an http connection that's purely on your local machine.

The error is misleading, but the failure is on your end.

**Comment by faho** [comment]
Alright, I just looked into adding https support here, and it's not feasible - the code to allow https is simple, but the certificate management is impossible. Either we add our own certificate and the browser will complain about it being self-signed (which clearly must be much worse than not signing at all), or we get a certificate from somewhere else and it has a much too low lifetime (it would have to last for the lifetime of the fish release, so somewhere in the five year range) - if we can even get away with shipping the private bit of the certificate.

Couple that with https providing, as far as I can see, exactly zero security here (it's all explicitly localhost-only already), and it's not something we're going to do for the foreseeable future.
