### ISSUE TITLE
Build failure due to Sphinx

### ISSUE THREAD

**Issue by xrisk** [fish-shell/fish-shell#8018]
I am trying to build fish from source, but I keep running into this issue:

```
rishav.kundu@gnode36:~/fish-3.2.2/build$ make
[  0%] Built target CHECK-FISH-BUILD-VERSION-FILE
[  0%] Built target build_fish_pc
[  1%] Built target pofiles_9
[  2%] Built target pofiles_7
[  2%] Built target pofiles_5
[  3%] Built target pofiles_1
[  4%] Built target pofiles_4
[  4%] Built target pofiles_8
[ 23%] Built target pcre2-32
[ 88%] Built target fishlib
[ 90%] Built target fish
[ 91%] Built target pofiles_3
[ 93%] Built target fish_indent
[ 95%] Built target fish_key_reader
[ 96%] Built target fish_test_helper
[ 97%] Built target pofiles_6
[ 97%] Built target pofiles_2
[ 98%] Building man pages with Sphinx

Exception occurred:
  File "/usr/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 266, in __getattr__
    raise AttributeError(name)
AttributeError: load_lexer_from_file
The full traceback has been saved in /tmp/sphinx-err-ct94lh.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
CMakeFiles/sphinx-manpages.dir/build.make:70: recipe for target 'CMakeFiles/sphinx-manpages' failed
make[2]: *** [CMakeFiles/sphinx-manpages] Error 1
CMakeFiles/Makefile2:1080: recipe for target 'CMakeFiles/sphinx-manpages.dir/all' failed
make[1]: *** [CMakeFiles/sphinx-manpages.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
```

The contents of the error log are:

```
rishav.kundu@gnode36:~/fish-3.2.2/build$ cat /tmp/sphinx-err-ct94lh.log
# Sphinx version: 1.3.6
# Python version: 2.7.12 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 150, in __init__
    self.config.setup(self)
  File "conf.py", line 50, in setup
  File "/usr/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 266, in __getattr__
    raise AttributeError(name)
AttributeError: load_lexer_from_file
```

I am not sure what is the problem here, and I don’t know enough CMake to debug. 

One potential issue that I can see is that CMake seems to be using Python 2? Is that intended?

**Comment by xrisk** [comment]
I *think* this is due to CMake picking up on the system installation of Python 2, which has a relatively old installation of Pygments (2.1). Unfortunately, I do not have root privileges on this system and upgrading system packages isn’t possible.

However, I *do* have a pyenv installation of Python 3.9 in my PATH before the system python2. Shouldn’t CMake be using that?

**Comment by xrisk** [comment]
Ideally, I would prefer not to build Sphinx docs at all. The README suggests this is possible:

> Sphinx is also optionally required to build the documentation from a cloned git repository.

However, I don’t see how to configure this.

**Comment by xrisk** [comment]
Alright, installing a newer version of Sphinx in my pyenv installation makes CMake pick it up. Sorry for the noise.

**Comment by faho** [comment]
>However, I don’t see how to configure this.

```
cmake -DBUILD_DOCS=OFF
```
