### ISSUE TITLE
make fail on python3.6

### ISSUE THREAD

**Issue by tensor-tang** [fish-shell/fish-shell#9000]
follow the compile steps but failed as below on `make -j`

```
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/home/username/tmp/fish-shell-3.4.1/doc_src/conf.py", line 198, in <module>
    man_pages.append((docname, cmd, get_command_description(path, cmd), "", 1))
  File "/home/username/tmp/fish-shell-3.4.1/doc_src/conf.py", line 164, in get_command_description
    for line in opened:
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1370: ordinal not in range(128)
```

env:
```
$ gcc --version
gcc (GCC) 8.5.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$python --version
Python 3.6.8
```

**Comment by tensor-tang** [comment]
Thanks a lot, resolved
